# Generated by Django 4.1.2 on 2022-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile_coins_profile_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flaps',
            field=models.IntegerField(default=0),
        ),
    ]
