# Generated by Django 4.1.2 on 2022-12-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_profile_flaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamesPlayed',
            field=models.IntegerField(default=0),
        ),
    ]
