# Generated by Django 4.1.5 on 2023-01-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_profile_currentbirdy_alter_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unlockedBirds',
            field=models.JSONField(default={'dark': False, 'default': True, 'green': False, 'lite': False, 'pink': False, 'red': False}),
        ),
    ]
