# Generated by Django 4.1.5 on 2023-01-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_defaultbirdy_profile_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkBlueBirdy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='static/images/birds/darkBirdy.png', upload_to='')),
                ('price', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='GreenBirdy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='static/images/birds/greenBirdy.png', upload_to='')),
                ('price', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='LiteBirdy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='static/images/birds/liteBirdy.png', upload_to='')),
                ('price', models.IntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='PinkBirdy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='static/images/birds/pinkBirdy.png', upload_to='')),
                ('price', models.IntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name='RedBirdy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='static/images/birds/redBirdy.png', upload_to='')),
                ('price', models.IntegerField(default=250)),
            ],
        ),
    ]
