# Generated by Django 4.1.5 on 2023-01-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_darkbluebirdy_greenbirdy_litebirdy_pinkbirdy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkbluebirdy',
            name='img',
            field=models.ImageField(default='static images/birds/darkBirdy.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='defaultbirdy',
            name='img',
            field=models.ImageField(default='static images/birdy.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='greenbirdy',
            name='img',
            field=models.ImageField(default='static images/birds/greenBirdy.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='litebirdy',
            name='img',
            field=models.ImageField(default='static images/birds/liteBirdy.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pinkbirdy',
            name='img',
            field=models.ImageField(default='static images/birds/pinkBirdy.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='redbirdy',
            name='img',
            field=models.ImageField(default='static images/birds/redBirdy.png', upload_to=''),
        ),
    ]
