# Generated by Django 4.1.5 on 2023-01-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_darkbluebirdy_img_alter_defaultbirdy_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkbluebirdy',
            name='img',
            field=models.ImageField(default='{%tatic images/birds/darkBirdy.png%}', upload_to=''),
        ),
        migrations.AlterField(
            model_name='defaultbirdy',
            name='img',
            field=models.ImageField(default="{% static 'images/birdy.png' %}", upload_to=''),
        ),
        migrations.AlterField(
            model_name='greenbirdy',
            name='img',
            field=models.ImageField(default='{%static images/birds/greenBirdy.png%}', upload_to=''),
        ),
    ]
