# Generated by Django 4.1.5 on 2023-01-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_darkbluebirdy_img_alter_defaultbirdy_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultbirdy',
            name='img',
            field=models.ImageField(default='images/birdy', upload_to=''),
        ),
    ]
