# Generated by Django 4.1.5 on 2023-01-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_defaultbirdy_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultbirdy',
            name='img',
            field=models.ImageField(default='images/birdy.png', upload_to=''),
        ),
    ]
