# Generated by Django 4.1.5 on 2023-01-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_defaultbirdy_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkbluebirdy',
            name='name',
            field=models.CharField(default='Dark Blue', max_length=20),
        ),
        migrations.AddField(
            model_name='defaultbirdy',
            name='name',
            field=models.CharField(default='Default', max_length=20),
        ),
        migrations.AddField(
            model_name='greenbirdy',
            name='name',
            field=models.CharField(default='Green', max_length=20),
        ),
        migrations.AddField(
            model_name='litebirdy',
            name='name',
            field=models.CharField(default='Lite Blue', max_length=20),
        ),
        migrations.AddField(
            model_name='pinkbirdy',
            name='name',
            field=models.CharField(default='Pink', max_length=20),
        ),
        migrations.AddField(
            model_name='redbirdy',
            name='name',
            field=models.CharField(default='Red', max_length=20),
        ),
        migrations.AlterField(
            model_name='darkbluebirdy',
            name='img',
            field=models.ImageField(default='images/birds/darkBirdy.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='greenbirdy',
            name='img',
            field=models.ImageField(default='images/birds/greenBirdy.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='litebirdy',
            name='img',
            field=models.ImageField(default='images/birds/liteBirdy.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pinkbirdy',
            name='img',
            field=models.ImageField(default='images/birds/pinkBirdy.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='redbirdy',
            name='img',
            field=models.ImageField(default='images/birds/redBirdy.png', upload_to=''),
        ),
    ]
