# Generated by Django 4.1.5 on 2023-01-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_profile_currentbirdy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkbluebirdy',
            name='img',
            field=models.CharField(default='images/birds/darkBirdy.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='defaultbirdy',
            name='img',
            field=models.CharField(default='images/birdy.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='greenbirdy',
            name='img',
            field=models.CharField(default='images/birds/greenBirdy.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='litebirdy',
            name='img',
            field=models.CharField(default='images/birds/liteBirdy.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='pinkbirdy',
            name='img',
            field=models.CharField(default='images/birds/pinkBirdy.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currentBirdy',
            field=models.CharField(default='images/birdy.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='redbirdy',
            name='img',
            field=models.CharField(default='images/birds/redBirdy.png', max_length=100),
        ),
    ]
