# Generated by Django 4.1.5 on 2023-01-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdys', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultBirdy',
        ),
    ]
